// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp36;

namespace WpfApp36.Migrations
{
    [DbContext(typeof(SettingContect))]
    [Migration("20191130073145_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("WpfApp36.KeyValue", b =>
                {
                    b.Property<int>("KeyValueID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("NameLeaDer");

                    b.Property<string>("NhanLuc");

                    b.HasKey("KeyValueID");

                    b.ToTable("KeyValues");
                });

            modelBuilder.Entity("WpfApp36.LineStatus", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LineName");

                    b.Property<string>("Mausac");

                    b.Property<int>("SanLuongChenh");

                    b.Property<int>("SanLuongThucTe");

                    b.Property<int>("SanLuongTuTao");

                    b.HasKey("LineId");

                    b.ToTable("LineStatuses");
                });

            modelBuilder.Entity("WpfApp36.MoDel", b =>
                {
                    b.Property<int>("ModelID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ModelLabel");

                    b.Property<string>("ModelName");

                    b.Property<int>("Production");

                    b.Property<int>("SumTime");

                    b.HasKey("ModelID");

                    b.ToTable("MoDels");
                });

            modelBuilder.Entity("WpfApp36.ModelTimer", b =>
                {
                    b.Property<int>("ModelTimerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ModelTimerName");

                    b.Property<string>("TimeAFrom");

                    b.Property<string>("TimeAFromNight");

                    b.Property<string>("TimeATo");

                    b.Property<string>("TimeAToNight");

                    b.Property<string>("TimeBFrom");

                    b.Property<string>("TimeBFromNight");

                    b.Property<string>("TimeBTo");

                    b.Property<string>("TimeBToNight");

                    b.Property<string>("TimeCFrom");

                    b.Property<string>("TimeCFromNight");

                    b.Property<string>("TimeCTo");

                    b.Property<string>("TimeCToNight");

                    b.Property<string>("TimeDFrom");

                    b.Property<string>("TimeDFromNight");

                    b.Property<string>("TimeDTo");

                    b.Property<string>("TimeDToNight");

                    b.Property<string>("TimeEFrom");

                    b.Property<string>("TimeEFromNight");

                    b.Property<string>("TimeETo");

                    b.Property<string>("TimeEToNight");

                    b.HasKey("ModelTimerId");

                    b.ToTable("ModelTimers");
                });
#pragma warning restore 612, 618
        }
    }
}
